Repository django-helpdesk/django-helpdesk, pull requests merged in 2019-02, with the labels that each got.

#715 User queues develop
  helpdesk/forms.py
  helpdesk/templates/helpdesk/cs/email_html_base.html
  helpdesk/templates/helpdesk/cs/email_text_footer.txt
  helpdesk/tests/test_ticket_actions.py
  helpdesk/views/staff.py
Labels: enhancement

#720 Add failing test case for issue-700 emails without bodies
  helpdesk/tests/test_files/blank-body-with-attachment.eml
  helpdesk/tests/test_files/pgp.eml
  helpdesk/tests/test_get_email.py
Labels: bug

#716 Cs translation
  helpdesk/fixtures/emailtemplate.json
  helpdesk/locale/cs/LC_MESSAGES/django.mo
  helpdesk/locale/cs/LC_MESSAGES/django.po
Labels: translations

#717 Basic support for tracking time spent on tickets and follow-ups
  helpdesk/admin.py
  helpdesk/migrations/0024_time_spent.py
  helpdesk/migrations/0025_queue_dedicated_time.py
  helpdesk/models.py
  helpdesk/serializers.py
  helpdesk/templates/helpdesk/followup_edit.html
  helpdesk/templates/helpdesk/report_index.html
  helpdesk/templates/helpdesk/ticket.html
  helpdesk/templates/helpdesk/ticket_desc_table.html
  helpdesk/templates/helpdesk/ticket_list.html
  helpdesk/templates/helpdesk/ticket_list_table.html
  helpdesk/tests/test_time_spent.py
  helpdesk/views/staff.py
Labels: feature-request
