Repository django-helpdesk/django-helpdesk, pull requests merged in 2020-06, with the labels that each got.

#830 Feature/dashboard pagination
  helpdesk/templates/helpdesk/dashboard.html
  helpdesk/templates/helpdesk/include/tickets.html
  helpdesk/views/staff.py
Labels: enhancement

#833 Update email templates fixtures
  helpdesk/fixtures/emailtemplate.json
Labels: bug, translations

#836 A ticket cannot depends on itself or on a ticket already depending on it
  helpdesk/views/staff.py
Labels: bug

#839 Fix KnowledgeBase item score
  helpdesk/models.py
  helpdesk/templates/helpdesk/kb_item.html
Labels: enhancement
