Repository django-helpdesk/django-helpdesk, pull requests merged in 2020-08, with the labels that each got.

#853 Update configuration.rst
  docs/configuration.rst
Labels: documentation

#855 Update kb_item.html
  helpdesk/templates/helpdesk/kb_item.html
Labels: bug

#854 Update kb_category.html
  helpdesk/templates/helpdesk/kb_category.html
Labels: bug

#856 added cancel changes button to edit ticket page
  helpdesk/templates/helpdesk/edit_ticket.html
Labels: enhancement

#860 Added endblock statement to ticket_list.html
  helpdesk/templates/helpdesk/ticket_list.html
Labels: bug

#863 Update kb_item.html
  helpdesk/templates/helpdesk/kb_item.html
Labels: enhancement

#862 Update kb_category.html
  helpdesk/templates/helpdesk/kb_category.html
Labels: enhancement
