Repository django-helpdesk/django-helpdesk, pull requests merged in 2020-10, with the labels that each got.

#876 Display a Total row in Reports
  helpdesk/templates/helpdesk/report_output.html
  helpdesk/views/staff.py
Labels: enhancement

#879 Update configuration.rst
  docs/configuration.rst
Labels: documentation

#869 Verify ticket.assigned_to is set before attempting to access id property
  helpdesk/views/staff.py
Labels: bug

#880 Update configuration.rst, again
  docs/configuration.rst
Labels: documentation

#882 Missing Migrations for 0.2.22
  helpdesk/migrations/0018_fix_migrations.py
Labels: bug

#881 Fix errors on master
  demo/demodesk/config/settings.py
  helpdesk/models.py
  helpdesk/query.py
  helpdesk/serializers.py
  helpdesk/views/staff.py
Labels: bug

#883 Updates required to work with Django 3.x
  helpdesk/decorators.py
  helpdesk/templates/helpdesk/base-head.html
  helpdesk/templates/helpdesk/base.html
  helpdesk/templates/helpdesk/base_js.html
  helpdesk/templates/helpdesk/filters/kbitems.html
  helpdesk/templates/helpdesk/filters/owner.html
  helpdesk/templates/helpdesk/filters/queue.html
  helpdesk/templates/helpdesk/filters/sorting.html
  helpdesk/templates/helpdesk/filters/status.html
  helpdesk/templates/helpdesk/public_base.html
  helpdesk/templates/helpdesk/public_view_ticket.html
  helpdesk/templates/helpdesk/report_output.html
  helpdesk/templates/helpdesk/rss_list.html
  helpdesk/templates/helpdesk/ticket.html
  helpdesk/templates/helpdesk/ticket_desc_table.html
  helpdesk/templates/helpdesk/ticket_list.html
  helpdesk/views/staff.py
Labels: bug

#884 update saved_queries imports, filter, and authentication checks, correct created field reference and remove Django version decrement
  helpdesk/query.py
  helpdesk/templatetags/saved_queries.py
  helpdesk/views/staff.py
  requirements.txt
Labels: bug

#885 email tests updated to correct references to functions
  helpdesk/tests/test_get_email.py
Labels: bug

#886 customizable navigation header template for override and documentation update
  docs/configuration.rst
  helpdesk/templates/helpdesk/custom_navigation_header.html
  helpdesk/templates/helpdesk/navigation-header.html
Labels: enhancement

#891 Fix Exception on sending mails with ticket attaches for non-file storages
  helpdesk/lib.py
Labels: bug

#892 Display custom fields with bootstrap `form-control` css class
  helpdesk/forms.py
Labels: enhancement

#893 Redirect to dashboard after deleting a ticket from there
  helpdesk/templates/helpdesk/delete_ticket.html
  helpdesk/templates/helpdesk/include/unassigned.html
  helpdesk/views/staff.py
Labels: bug

#894 Improvements in Public part
  helpdesk/forms.py
  helpdesk/static/helpdesk/helpdesk-extend.css
  helpdesk/static/helpdesk/js/init_due_date.js
  helpdesk/templates/helpdesk/create_ticket.html
  helpdesk/templates/helpdesk/include/alert_form_errors.html
  helpdesk/templates/helpdesk/public_create_ticket.html
  helpdesk/templates/helpdesk/public_create_ticket_base.html
  helpdesk/templates/helpdesk/public_homepage.html
  helpdesk/templates/helpdesk/public_view_ticket.html
  helpdesk/views/public.py
Labels: bug

#896 Improvements in Ticketcc views and templates
  helpdesk/models.py
  helpdesk/templates/helpdesk/ticket_cc_add.html
  helpdesk/templates/helpdesk/ticket_cc_list.html
  helpdesk/views/staff.py
Labels: enhancement
