Repository django-helpdesk/django-helpdesk, pull requests merged in 2020-11, with the labels that each got.

#895 New feature: Merging tickets
  helpdesk/email.py
  helpdesk/forms.py
  helpdesk/lib.py
  helpdesk/locale/fr/LC_MESSAGES/django.mo
  helpdesk/locale/fr/LC_MESSAGES/django.po
  helpdesk/migrations/0033_ticket_merged_to.py
  helpdesk/migrations/0034_create_email_template_for_merged.py
  helpdesk/models.py
  helpdesk/templated_email.py
  helpdesk/templates/helpdesk/include/ticket_merge_row.html
  helpdesk/templates/helpdesk/include/unassigned.html
  helpdesk/templates/helpdesk/ticket.html
  helpdesk/templates/helpdesk/ticket_desc_table.html
  helpdesk/templates/helpdesk/ticket_list.html
  helpdesk/templates/helpdesk/ticket_merge.html
  helpdesk/templatetags/helpdesk_util.py
  helpdesk/tests/test_ticket_actions.py
  helpdesk/tests/test_ticket_lookup.py
  helpdesk/urls.py
  helpdesk/views/staff.py
Labels: enhancement

#898 Fix Ticket List
  helpdesk/locale/fr/LC_MESSAGES/django.mo
  helpdesk/locale/fr/LC_MESSAGES/django.po
  helpdesk/static/helpdesk/filter.js
  helpdesk/static/helpdesk/helpdesk-customize.css
  helpdesk/templates/helpdesk/ticket_list.html
Labels: bug

#901 fix(migrations): Fix the 0034 migration for Postgres
  helpdesk/migrations/0018_ticket_secret_key.py
  helpdesk/migrations/0019_ticket_secret_key.py
  helpdesk/migrations/0034_create_email_template_for_merged.py
Labels: bug

#904 Allow users to edit tickets if HELPDESK_ALLOW_NON_STAFF_TICKET_UPDATE enabled
  helpdesk/user.py
Labels: bug

#905 Allow users to edit tickets if HELPDESK_ALLOW_NON_STAFF_TICKET_UPDATE enabled
  helpdesk/views/staff.py
Labels: bug

#907 Timeline 3 license
  LICENSE.3RDPARTY
Labels: documentation

#909 fix(tests): Run tests without the socks components and document theirusage
  README.rst
  helpdesk/tests/test_get_email.py
  quicktest.py
Labels: enhancement
