Repository django-helpdesk/django-helpdesk, pull requests merged in 2021-02, with the labels that each got.

#937 Formerly RFC 5322 "r" format changed to "DATETIME_FORMAT"
  helpdesk/templates/helpdesk/include/tickets.html
  helpdesk/templates/helpdesk/include/unassigned.html
  helpdesk/templates/helpdesk/public_view_ticket.html
  helpdesk/templates/helpdesk/ticket.html
Labels: enhancement

#940 Tool tips improved, KB Contact Human Button replaced
  helpdesk/templates/helpdesk/kb_category_base.html
  helpdesk/templates/helpdesk/ticket_desc_table.html
Labels: enhancement

#939 Template hard coded date filters replaced with Django DATETIME_FORMAT
  helpdesk/fixtures/emailtemplate.json
Labels: enhancement

#932 Fix import of celery decorator "task".
  helpdesk/tasks.py
Labels: bug

#941 Disabled merged_to field in edit ticket + Fix datepicker
  helpdesk/forms.py
  helpdesk/templates/helpdesk/edit_ticket.html
  helpdesk/views/staff.py
Labels: enhancement

#944 Merged to
  helpdesk/forms.py
  helpdesk/templates/helpdesk/edit_ticket.html
  helpdesk/views/staff.py
Labels: bug

#946 CustomField datetime type formats updated to fixed string formats
  helpdesk/forms.py
  helpdesk/static/helpdesk/js/init_datetime_classes.js
  helpdesk/static/helpdesk/js/init_due_date.js
  helpdesk/templates/helpdesk/edit_ticket.html
  helpdesk/templates/helpdesk/ticket_desc_table.html
  helpdesk/templatetags/helpdesk_util.py
  helpdesk/tests/test_kb.py
  helpdesk/views/staff.py
Labels: bug, enhancement
