Repository django-helpdesk/django-helpdesk, pull requests merged in 2022-08, with the labels that each got.

#1045 Dissable to disable
  docs/teams.rst
Labels: documentation

#1046 Workflow cache
  .github/workflows/pythonpackage.yml
  requirements.txt
Labels: enhancement

#1047 Workflow cache
  .github/workflows/pythonpackage.yml
Labels: enhancement

#1038 fix to use latest markdown and add tests
  helpdesk/models.py
  helpdesk/tests/test_markdown.py
Labels: bug
